### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by TJM** [major/rackspace-clouddns-gui#11]
While this application should never be exposed to the "outside world" (matter of fact it should be bound to 127.0.0.1), I still think it would be smart to put some basic input validation in place. Obviously invalid stuff will fail when exposed to the rackspace API, but it would be good to catch it before hand and alert on it.

**Comment by major** [comment]
I could definitely see making the Flask app start on 127.0.0.1 by default, but what type of input validation are you thinking about?  If it's totally invalid, the API will reject it with a 400 (or similar).

**Comment by TJM** [comment]
Domain name, records, etc with invalid characters, priorities that are non-numeric, etc.

I always try to think of things from a security perspective, i.e. what could a person with mal-intent do to break this app.

In my https://github.com/TommyTheKid/rackspace-clouddns-gui/branches/ApplyDNSTemplate branch, for example, I won't let it take raw input (templateName) and expose it to the command line (to open the template file). I need to figure out a way to ensure that is "fairly safe" before doing that :)

**Comment by TJM** [comment]
RE: 127.0.0.1 -- I would recommend it, It is almost too small to do a branch/pull request, but if you want, I will :)
