### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by major** [major/rackspace-clouddns-gui#3]
Should responses from the DNS API be cached for faster access?  Should AJAX be used?

**Comment by TJM** [comment]
If there is a caching mechanism, there needs to be a way to force a refresh. (button)

RE: AJAX: We had a suggestion for using AJAX during the updates of records. That seems like it would lend itself to AJAX really well.

**Comment by TJM** [comment]
Another place that would be nice to see something (AJAX-ish?) is during longer operations, a "working" indicator... if you have PYTHON_CLOUDDNS_DEBUG enabled, you can see what its doing, but otherwise you are blind.
